### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by getData123** [devbret/geospy-api-mapping#1]
Hello, 

I used this picture in Egypt: https://www.tadamun.co/wp-content/uploads/2016/07/01-DSC_50221.jpg

I am getting this error:

`C:\Users>app.py
2024-03-12 19:52:20,301 - DEBUG: Using proactor: IocpProactor
2024-03-12 19:52:27,190 - DEBUG: Request successful for C:/Users/Sarab/Downloads/geospy-api-mapping-main/images.jpg: {'status': 200, 'message': 'Success', 'geo_predictions': [{'coordinates': [30.05019760131836, 31.260866165161133], 'score': 0.026871943846344948, 'similarity_score_1km': 95.0}, {'coordinates': [30.047815322875977, 31.26133918762207], 'score': 0.026474211364984512, 'similarity_score_1km': 93.59390202862528}, {'coordinates': [30.04784393310547, 31.261606216430664], 'score': 0.026226885616779327, 'similarity_score_1km': 92.71953483681199}, {'coordinates': [30.047883987426758, 31.262197494506836], 'score': 0.025633465498685837, 'similarity_score_1km': 90.62162515297089}, {'coordinates': [30.046510696411133, 31.240610122680664], 'score': 0.025533528998494148, 'similarity_score_1km': 90.26832106851397}, {'coordinates': [30.047666549682617, 31.262165069580078], 'score': 0.0255025252699852, 'similarity_score_1km': 90.158714029098}, {'coordinates': [30.052452087402344, 31.260223388671875], 'score': 0.02549625188112259, 'similarity_score_1km': 90.13653580688394}, {'coordinates': [30.04446792602539, 31.23582649230957], 'score': 0.02482173964381218, 'similarity_score_1km': 87.75194231000506}, {'coordinates': [30.04405975341797, 31.23625946044922], 'score': 0.0248145442456007, 'similarity_score_1km': 87.72650452128387}, {'coordinates': [30.045766830444336, 31.260244369506836], 'score': 0.024791929870843887, 'similarity_score_1km': 87.64655624459122}]}
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000228577FC700>
Traceback (most recent call last):
  File "C:\Users\Sarab\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Sarab\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Sarab\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\Sarab\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`

When I opened index.html I didn't get the location

Can you please tell me what I am doing wrong
Thanks

**Comment by getData123** [comment]
The api_responses.json looks like this:

`[{"C:/Users/Sarab/Downloads/geospy-api-mapping-main/images.jpg": {"status": 200, "message": "Success", "geo_predictions": [{"coordinates": [30.05019760131836, 31.260866165161133], "score": 0.026871943846344948, "similarity_score_1km": 95.0}, {"coordinates": [30.047815322875977, 31.26133918762207], "score": 0.026474211364984512, "similarity_score_1km": 93.59390202862528}, {"coordinates": [30.04784393310547, 31.261606216430664], "score": 0.026226885616779327, "similarity_score_1km": 92.71953483681199}, {"coordinates": [30.047883987426758, 31.262197494506836], "score": 0.025633465498685837, "similarity_score_1km": 90.62162515297089}, {"coordinates": [30.046510696411133, 31.240610122680664], "score": 0.025533528998494148, "similarity_score_1km": 90.26832106851397}, {"coordinates": [30.047666549682617, 31.262165069580078], "score": 0.0255025252699852, "similarity_score_1km": 90.158714029098}, {"coordinates": [30.052452087402344, 31.260223388671875], "score": 0.02549625188112259, "similarity_score_1km": 90.13653580688394}, {"coordinates": [30.04446792602539, 31.23582649230957], "score": 0.02482173964381218, "similarity_score_1km": 87.75194231000506}, {"coordinates": [30.04405975341797, 31.23625946044922], "score": 0.0248145442456007, "similarity_score_1km": 87.72650452128387}, {"coordinates": [30.045766830444336, 31.260244369506836], "score": 0.024791929870843887, "similarity_score_1km": 87.64655624459122}]}}]`

**Comment by devbret** [comment]
Hello and thank you for using the app, as well as for opening a ticket. I hope to help you resolve this issue. 

I have pushed a change that should resolve the issues you are having with the runtime error. Please update your local code from this repo, then try processing the data again and then visualizing it using the index.html file.

If that doesn't work definitely let me know and I will work with you to get a fix.

**Comment by getData123** [comment]
Thank you very much

The error still there with the change

I went to this: https://stackoverflow.com/questions/45600579/asyncio-event-loop-is-closed-when-getting-loop

Because he said: "You have already called loop.close() before you ran that sample piece of code, on the global event loop:...You need to create a new loop:" tried to change but I got errors

The map is working great it didn't effect the result

**Comment by devbret** [comment]
Hello. I have made a change to the index.html file that might solve your problem. Can you pull the latest version of this app, and try again?

**Comment by getData123** [comment]
Thank you very much, I will try it now and tell you

**Comment by getData123** [comment]
Thank you very much. It worked. I really appreciate it.

![Untitled](https://github.com/devbret/geospy-api-mapping/assets/101978587/ba27d6cc-e278-44ed-8cf5-862edc1213bf)

**Comment by devbret** [comment]
Outstanding! I am happy to hear that. You are most welcome. I will go ahead and close this ticket.
